site_name: My Docs

theme:
  name: material
  language: en

repo_name: 0x326/miami-university-senior-capstone-project
repo_url: https://gitlab.com/0x326/miami-university-senior-capstone-project
edit_uri: /-/edit/master/docs/

nav:
  - Installation: index.md
  - Contributing: CONTRIBUTING.md
  - Hardware: HARDWARE.md
  - SRC:
    - web: web/globals.md
    - scale-interface: scale-interface/globals.md
  - License: license.md
