site_name: My Docs

theme:
  name: material
  language: en

repo_name: 0x326/miami-university-senior-capstone-project
repo_url: https://gitlab.com/0x326/miami-university-senior-capstone-project
edit_uri: /-/edit/master/docs/

nav:
  - Installation: index.md
  - Contributing: CONTRIBUTING.md
  - Hardware: HARDWARE.md
  - SRC:
    - web:
      - overview: web/README.md
      - detailed: web/globals.md
    - scale-interface:
      - overview: scale-interface/README.md
      - detailed: scale-interface/globals.md
    - api-interfaces:
      - overview: api-interfaces/README.md
      - detailed: api-interfaces/globals.md
  - License: license.md
