parserOptions:
  project: ./tsconfig.json

env:
  browser: true
  node: true
  jest: true

overrides:
  - files:
    - 'src/serviceWorker.ts'

    rules:
      # create-react-app does not allow us to reference this in a eslint-disable comment
      # See https://github.com/facebook/create-react-app/issues/7712#issuecomment-543368918
      unicorn/no-unsafe-regex: off
      security/detect-unsafe-regex: off

  - files:
    - 'src/xlsx.ts'

    rules:
      security/detect-object-injection: off
      unicorn/prefer-spread: off # because using spread causes other issues

  - files:
    - 'src/AppModalDrawer.tsx'

    rules:
      unicorn/prevent-abbreviations:
        - error
        - replacements:
            props: false
            params:
              parameters: false
