name: scale-interface
version: git
summary: Bridge to AND scale
description: |
  For options:-
    $ scale-interface --help

confinement: devmode
base: core18

parts:
  scale-interface:
    plugin: nodejs
    source: .

apps:
  scale-interface:
    command: scale-interface
